// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trabalho_de_Gerenciamento.Data;

#nullable disable

namespace Trabalho_de_Gerenciamento.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910165526_SeedPacientes")]
    partial class SeedPacientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trabalho_de_Gerenciamento.Models.Pacientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "667.990.787-90",
                            DataNascimento = new DateTime(1990, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Endereco = "Rua Alberto Biason, 12",
                            Nome = "João Silva",
                            Telefone = "18998787654"
                        },
                        new
                        {
                            Id = 2,
                            CPF = "231.231.241-24",
                            DataNascimento = new DateTime(1991, 8, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Endereco = "Rua Lucas Teodoro, 60",
                            Nome = "Mateus Sousa",
                            Telefone = "18999095432"
                        },
                        new
                        {
                            Id = 3,
                            CPF = "123.456.789-00",
                            DataNascimento = new DateTime(1985, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Endereco = "Rua Gabriel Domingues, 39",
                            Nome = "Maria Oliveira",
                            Telefone = "18995456789"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
